<script lang="ts">
  import clsx from 'clsx';
  import { getContext, onMount } from 'svelte';
  import { fade } from 'svelte/transition';

  import { contextKey } from '../app.svelte';

  export let selectedIcon: string;

  let root: HTMLDivElement;
  let icons = [
    'icon-chain',
    'icon-chain-slash',
    'icon-arrow-u-right',
    'icon-arrow-u-left',
    'icon-arrow-down',
    'icon-arrow-up',
    'icon-arrow-left',
    'icon-arrow-right',
    'icon-arrow-down-circle',
    'icon-arrow-left-circle',
    'icon-arrow-right-circle',
    'icon-arrow-up-circle',
    'icon-arrow-left-rect',
    'icon-arrow-right-rect',
    'icon-arrow-crooked-left',
    'icon-arrow-crooked-right',
    'icon-arrow-double-left',
    'icon-arrow-double-right',
    'icon-arrow-down-line',
    'icon-arrow-up-line',
    'icon-arrows',
    'icon-arrows-h',
    'icon-arrows-v',
    'icon-magnifier',
    'icon-magnifier-minus',
    'icon-magnifier-plus',
    'icon-merge',
    'icon-separate',
    'icon-market',
    'icon-bubble-o',
    'icon-bubble-times',
    'icon-clapperboard',
    'icon-collapse',
    'icon-collapse-scheme',
    'icon-dialog-window',
    'icon-dialog-window-cogwheel',
    'icon-doc-ban-sign',
    'icon-doc-o',
    'icon-doc-user',
    'icon-expand',
    'icon-file',
    'icon-folder-belt',
    'icon-folder-o',
    'icon-hat-moustache',
    'icon-key',
    'icon-rectangle-a',
    'icon-rectangle-a-o',
    'icon-rectangle-o-h',
    'icon-rectangle-o-v',
    'icon-rectangle-paragraph',
    'icon-tab',
    'icon-file-pdf',
    'icon-graduate-cap',
    'icon-clipboard-list',
    'icon-user-checkbox',
    'icon-box-cart',
    'icon-bubble-censored',
    'icon-drawers',
    'icon-earth',
    'icon-form',
    'icon-invoice',
    'icon-mug',
    'icon-square-dashed-line',
    'icon-briefcase',
    'icon-funnel',
    'icon-map',
    'icon-notebook',
    'icon-piechart',
    'icon-user-frame',
    'icon-clipboard-checklist',
    'icon-pictures',
    'icon-flag',
    'icon-folder',
    'icon-folder-opened',
    'icon-picture',
    'icon-bin',
    'icon-bubble',
    'icon-doc',
    'icon-doc-move',
    'icon-edit',
    'icon-menu',
    'icon-message',
    'icon-user',
    'icon-monitor-broken',
    'icon-monitor',
    'icon-chevron-down-line',
    'icon-chevron-left-line',
    'icon-chevron-right-line',
    'icon-chevron-up-line',
    'icon-pin-o',
    'icon-brand-sharepoint',
    'icon-heartshake',
    'icon-pin',
    'icon-checklist',
    'icon-watch',
    'icon-permission-list',
    'icon-users',
    'icon-brand-youtube',
    'icon-brand-pinterest',
    'icon-brand-open-id',
    'icon-two-rectangles-v',
    'icon-brand-linkedin',
    'icon-two-rectangles-h',
    'icon-brand-google-plus',
    'icon-t-shirt',
    'icon-xml-tag',
    'icon-truck',
    'icon-trophy',
    'icon-rss',
    'icon-triangle-right',
    'icon-restriction-list',
    'icon-translate',
    'icon-qr-code',
    'icon-times-circle',
    'icon-lock-unlocked',
    'icon-times',
    'icon-dollar-sign',
    'icon-tag',
    'icon-tablet',
    'icon-cb-check-disabled',
    'icon-table',
    'icon-carousel',
    'icon-star-full',
    'icon-star-semi',
    'icon-star-empty',
    'icon-arrows-crooked',
    'icon-staging-scheme',
    'icon-shopping-cart',
    'icon-highlighter',
    'icon-square-dashed',
    'icon-cookie',
    'icon-square',
    'icon-software-package',
    'icon-smartphone',
    'icon-scissors',
    'icon-rotate-right',
    'icon-rotate-left',
    'icon-rotate-double-right',
    'icon-ribbon',
    'icon-rb-uncheck',
    'icon-rb-check-sign',
    'icon-question-circle',
    'icon-project-scheme',
    'icon-process-scheme',
    'icon-plus-square',
    'icon-plus-circle',
    'icon-plus',
    'icon-placeholder',
    'icon-perfume',
    'icon-percent-sign',
    'icon-pda',
    'icon-pc',
    'icon-pause',
    'icon-parent-children-scheme',
    'icon-paperclip',
    'icon-pants',
    'icon-palette',
    'icon-organisational-scheme',
    'icon-newspaper',
    'icon-monitor-smartphone',
    'icon-modal-question',
    'icon-modal-minimize',
    'icon-modal-maximize',
    'icon-modal-close',
    'icon-minus-circle',
    'icon-microphone',
    'icon-messages',
    'icon-media-player',
    'icon-mask',
    'icon-map-marker',
    'icon-lock',
    'icon-life-belt',
    'icon-laptop',
    'icon-kentico',
    'icon-integration-scheme',
    'icon-i-circle',
    'icon-chevron-up-square',
    'icon-chevron-up-circle',
    'icon-chevron-up',
    'icon-chevron-right-square',
    'icon-chevron-right',
    'icon-chevron-left-square',
    'icon-chevron-left-circle',
    'icon-chevron-left',
    'icon-chevron-down-square',
    'icon-chevron-down-circle',
    'icon-chevron-down',
    'icon-chevron-double-up',
    'icon-chevron-double-right',
    'icon-chevron-double-left',
    'icon-chevron-double-down',
    'icon-checklist2',
    'icon-check-circle',
    'icon-check',
    'icon-tags',
    'icon-shoe-women',
    'icon-printer',
    'icon-parent-child-scheme',
    'icon-minus-square',
    'icon-light-bulb',
    'icon-chevron-right-circle',
    'icon-home',
    'icon-half-arrows-right-left',
    'icon-graph',
    'icon-factory',
    'icon-exclamation-triangle',
    'icon-ellipsis',
    'icon-ekg-line',
    'icon-doc-paste',
    'icon-doc-copy',
    'icon-database',
    'icon-cup',
    'icon-compass',
    'icon-cogwheel-square',
    'icon-cogwheels',
    'icon-cogwheel',
    'icon-circle-square',
    'icon-circle',
    'icon-cb-uncheck',
    'icon-cb-check-sign',
    'icon-caret-up',
    'icon-caret-right-down',
    'icon-caret-right',
    'icon-caret-left',
    'icon-caret-down',
    'icon-camera',
    'icon-calendar-number',
    'icon-calendar',
    'icon-bullseye',
    'icon-building-block',
    'icon-building',
    'icon-bug',
    'icon-bucket-shovel',
    'icon-bubbles',
    'icon-brush',
    'icon-broom',
    'icon-brand-twitter',
    'icon-brand-google',
    'icon-brand-facebook',
    'icon-brand-bing',
    'icon-braces',
    'icon-boxes',
    'icon-box',
    'icon-ban-sign',
    'icon-badge',
    'icon-arrow-right-top-square',
    'icon-breadcrumb',
    'icon-clock',
    'icon-cloud',
    'icon-cb-check-preview',
    'icon-accordion',
    'icon-two-squares-line',
    'icon-money-bill',
    'icon-puzzle',
    'icon-wizard-stick',
    'icon-lines-rectangle-o',
    'icon-doc-arrows',
    'icon-l-text-col',
    'icon-l-menu-text-col',
    'icon-l-menu-cols-3',
    'icon-l-logotype-menu-v-col',
    'icon-l-logotype-menu-h-col',
    'icon-l-header-cols-3-footer',
    'icon-l-cols-80-20',
    'icon-l-cols-20-80',
    'icon-l-cols-4',
    'icon-l-cols-3',
    'icon-l-cols-2',
    'icon-bezier-scheme',
    'icon-note',
    'icon-piechart-lines',
    'icon-l-article-map',
    'icon-l-calendar-number-article',
    'icon-l-forms-2',
    'icon-l-header-cols-2-footer',
    'icon-l-header-list-img',
    'icon-l-header-menu-text',
    'icon-l-header-text',
    'icon-l-list-article',
    'icon-l-lightbox',
    'icon-l-img-3-cols-3',
    'icon-l-img-2-cols-3',
    'icon-l-text',
    'icon-l-rows-4',
    'icon-l-rows-3',
    'icon-l-rows-2',
    'icon-l-menu-text-col-bottom',
    'icon-l-menu-text',
    'icon-l-menu-list-img-col',
    'icon-l-menu-list-img',
    'icon-l-menu-list',
    'icon-l-menu-cols-2',
    'icon-l-logotype-menu-col-footer',
    'icon-l-list-title',
    'icon-l-list-img-article',
    'icon-l-list-article-col',
    'icon-tree-structure',
    'icon-vb',
    'icon-crosshair-o',
    'icon-crosshair-f',
    'icon-caret-right-aligned-left',
    'icon-caret-left-aligned-right',
    'icon-gauge',
    'icon-c-sharp',
    'icon-tab-vertical',
    'icon-right-double-quotation-mark',
    'icon-braces-octothorpe',
    'icon-outdent',
    'icon-indent',
    'icon-i',
    'icon-b',
    'icon-u',
    'icon-s',
    'icon-x',
    'icon-t-f',
    'icon-t',
    'icon-parent-child-scheme-2',
    'icon-parent-child-scheme2',
    'icon-doc-torn',
    'icon-f',
    'icon-a-lowercase',
    'icon-circle-slashed',
    'icon-one',
    'icon-diamond',
    'icon-choice-user-scheme',
    'icon-choice-single-scheme',
    'icon-choice-multi-scheme',
    'icon-book-opened',
    'icon-e-book',
    'icon-spinner',
    'icon-layouts',
    'icon-layout',
    'icon-id-card',
    'icon-id-cards',
    'icon-l-grid-3-2',
    'icon-l-grid-2-2',
    'icon-l-cols-70-30',
    'icon-l-cols-30-70',
    'icon-l-cols-25-50-25',
    'icon-l-cols-20-60-20',
    'icon-eye',
    'icon-list',
    'icon-folder-clock',
  ];

  onMount(() => {
    const selected = root.querySelector('.selected');

    if (selected) {
      selected.scrollIntoView();
    }
  });

  const { resources } = getContext(contextKey);
</script>

<div bind:this={root} class="root group column">
  {#each icons as icon}
    <div
      class={clsx('icon', icon)}
      class:selected={icon === selectedIcon}
      title={icon}
      on:click={() => (selectedIcon = icon)}
    />
  {/each}
</div>

<style>
  .group {
    display: flex;
  }

  .column {
    flex-direction: column;
  }

  .item {
    flex: 1;
  }

  .root {
    text-align: center;
    box-sizing: border-box;
    margin: 0.2em 0;
    padding: 0.2em 0em;
    overflow-y: auto;
  }

  .icon {
    height: 1.8em;
    line-height: 1.4em;
    padding: 0.1em;
    width: 1.8em;
    text-align: center;
    box-sizing: border-box;
    margin: 0.1em;
    align-self: center;
    border-radius: 0.2em;
  }

  .icon.selected {
    background: #a3a2a2;
  }
</style>
